# Generated by Django 5.2.8 on 2025-12-03 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('trigger_event', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaybookStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('SEND_SMS', 'Send SMS'), ('SEND_EMAIL', 'Send Email'), ('ASSIGN_TASK', 'Assign Task'), ('WAIT', 'Wait')], max_length=20)),
                ('action_config', models.JSONField(default=dict, help_text='Config for the action (e.g., message template)')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='customer_success.playbook')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomerJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='customers.customer')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_success.playbook')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_success.playbookstep')),
            ],
        ),
    ]
