# Generated by Django 5.2.8 on 2025-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_transaction_alter_pricingplan_id_alter_voucher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
