# Generated by Django 5.2.8 on 2025-12-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_transaction_checkout_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
