# Generated by Django 5.2.8 on 2025-12-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkQualityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_id', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('latency_ms', models.FloatField()),
                ('jitter_ms', models.FloatField()),
                ('packet_loss_percent', models.FloatField()),
                ('cpu_usage_percent', models.FloatField(default=0.0)),
                ('memory_usage_percent', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('CONFIRMED', 'Confirmed'), ('RESOLVED', 'Resolved')], default='DETECTED', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('estimated_fix_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
