# Generated by Django 5.2.8 on 2025-12-03 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('GOOD', 'Good'), ('CONGESTED', 'Congested'), ('OUTAGE', 'Outage'), ('MAINTENANCE', 'Maintenance')], default='GOOD', max_length=20)),
                ('avg_speed_mbps', models.FloatField(default=0.0)),
                ('uptime_percent', models.FloatField(default=100.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransparencyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('THROTTLE', 'Throttling Applied'), ('UPGRADE', 'Network Upgrade'), ('OUTAGE', 'Outage Report'), ('ALERT', 'Proactive Alert')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transparency_logs', to='customers.customer')),
            ],
        ),
    ]
