# Generated by Django 5.2.8 on 2025-12-03 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_transaction_alter_pricingplan_id_alter_voucher_id'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='social_billing.groupmember')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_groups', to='customers.customer')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.pricingplan')),
            ],
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='social_billing.groupplan'),
        ),
        migrations.CreateModel(
            name='CostSplitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_type', models.CharField(choices=[('EQUAL', 'Equal Split'), ('USAGE', 'Usage Based'), ('CUSTOM', 'Custom Percentage')], default='EQUAL', max_length=20)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_splitter', to='social_billing.groupplan')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'customer')},
        ),
    ]
